app:
  token:
    expirationTime: ${TOKEN_EXPIRATION_TIME}
    secret: ${TOKEN_SECRET_KEY}
  record:
    maxParsingDuration: ${MAX_PARSE_DURATION:15s}
  storage:
    temp-store-path: ${TEMP_STORE_PATH}
    regular-store-path: ${REGULAR_STORE_PATH}
    file-name-pattern: "{FILE_HASH}_{TIMESTAMP}_{USER_UPLOADED}.{EXTENSION}"

server:
  port: ${SERVER_PORT:8000}
  error:
    include-message: always

spring:
  mvc:
    async:
      request-timeout: ${MAX_REQUEST_TIMEOUT:30s}
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:10MB}
      max-request-size: ${MAX_FILE_SIZE:10MB}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
  security:
    filter:
      order: 10
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQLDialect
