package org.singing.app.ui.theme

import androidx.compose.ui.graphics.Color


val primaryLight = Color(0xFF00919E)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF9DF0FC)
val onPrimaryContainerLight = Color(0xFF001F23)
val secondaryLight = Color(0xFF397FD3)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFC9E2FF)
val onSecondaryContainerLight = Color(0xFF001C3B)
val tertiaryLight = Color(0xFF4A662C)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFBFED8B)
val onTertiaryContainerLight = Color(0xFF0F2000)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFF5FAFB)
val onBackgroundLight = Color(0xFF171D1E)
val surfaceLight = Color(0xFFF5FAFB)
val onSurfaceLight = Color(0xFF171D1E)
val surfaceVariantLight = Color(0xFFDBE4E6)
val onSurfaceVariantLight = Color(0xFF3F484A)
val outlineLight = Color(0xFF6F797A)
val outlineVariantLight = Color(0xFFBEC8CA)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2B3132)
val inverseOnSurfaceLight = Color(0xFFECF2F3)
val inversePrimaryLight = Color(0xFF81D3DF)

val primaryFixedLight = Color(0xFF9DF0FC)
val onPrimaryFixedLight = Color(0xFF001F23)
val primaryFixedDimLight = Color(0xFF81D3DF)
val onPrimaryFixedVariantLight = Color(0xFF004F57)
val secondaryFixedLight = Color(0xFFD5E3FF)
val onSecondaryFixedLight = Color(0xFF001C3B)
val secondaryFixedDimLight = Color(0xFFA6C8FF)
val onSecondaryFixedVariantLight = Color(0xFF234776)
val tertiaryFixedLight = Color(0xFFCBEDA5)
val onTertiaryFixedLight = Color(0xFF0F2000)
val tertiaryFixedDimLight = Color(0xFFB0D18B)
val onTertiaryFixedVariantLight = Color(0xFF344E17)
val mainBannerScrimLight = Color(0x824E7477)

val surfaceDimLight = Color(0xFFD5DBDC)
val surfaceBrightLight = Color(0xFFF5FAFB)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFEFF5F5)
val surfaceContainerLight = Color(0xFFE9EFF0)
val surfaceContainerHighLight = Color(0xFFE3E9EA)
val surfaceContainerHighestLight = Color(0xFFDEE4E4)


val primaryDark = Color(0xFF81D3DF)
val onPrimaryDark = Color(0xFF00363C)
val primaryContainerDark = Color(0xFF004F57)
val onPrimaryContainerDark = Color(0xFF9DF0FC)
val secondaryDark = Color(0xFFA6C8FF)
val onSecondaryDark = Color(0xFF02315E)
val secondaryContainerDark = Color(0xFF234776)
val onSecondaryContainerDark = Color(0xFFD5E3FF)
val tertiaryDark = Color(0xFFB0D18B)
val onTertiaryDark = Color(0xFF1E3702)
val tertiaryContainerDark = Color(0xFF344E17)
val onTertiaryContainerDark = Color(0xFFCBEDA5)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF0E1415)
val onBackgroundDark = Color(0xFFDEE4E4)
val surfaceDark = Color(0xFF0E1415)
val onSurfaceDark = Color(0xFFDEE4E4)
val surfaceVariantDark = Color(0xFF3F484A)
val onSurfaceVariantDark = Color(0xFFBEC8CA)
val outlineDark = Color(0xFF899294)
val outlineVariantDark = Color(0xFF3F484A)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFDEE4E4)
val inverseOnSurfaceDark = Color(0xFF2B3132)
val inversePrimaryDark = Color(0xFF006973)

val primaryFixedDark = Color(0xFF9DF0FC)
val onPrimaryFixedDark = Color(0xFF001F23)
val primaryFixedDimDark = Color(0xFF81D3DF)
val onPrimaryFixedVariantDark = Color(0xFF004F57)
val secondaryFixedDark = Color(0xFFD5E3FF)
val onSecondaryFixedDark = Color(0xFF001C3B)
val secondaryFixedDimDark = Color(0xFFA6C8FF)
val onSecondaryFixedVariantDark = Color(0xFF234776)
val tertiaryFixedDark = Color(0xFFCBEDA5)
val onTertiaryFixedDark = Color(0xFF0F2000)
val tertiaryFixedDimDark = Color(0xFFB0D18B)
val onTertiaryFixedVariantDark = Color(0xFF344E17)
val mainBannerScrimDark = Color(0xFF4E7477)

val surfaceDimDark = Color(0xFF0E1415)
val surfaceBrightDark = Color(0xFF343A3B)
val surfaceContainerLowestDark = Color(0xFF090F10)
val surfaceContainerLowDark = Color(0xFF171D1E)
val surfaceContainerDark = Color(0xFF1B2122)
val surfaceContainerHighDark = Color(0xFF252B2C)
val surfaceContainerHighestDark = Color(0xFF303637)
