package com.singing.app.ui.theme

import androidx.compose.ui.graphics.Color

val primaryFixedLight = Color(0xFFD2DCFF)
val onPrimaryFixedLight = Color(0xFF001A43)
val primaryFixedDimLight = Color(0xFFA0BCFF)
val onPrimaryFixedVariantLight = Color(0xFF2D4678)
val secondaryFixedLight = Color(0xFFAEECFF)
val onSecondaryFixedLight = Color(0xFF001F26)
val secondaryFixedDimLight = Color(0xFF85D2E7)
val onSecondaryFixedVariantLight = Color(0xFF004E5D)
val tertiaryFixedLight = Color(0xFFFFD9DF)
val onTertiaryFixedLight = Color(0xFF3A0717)
val tertiaryFixedDimLight = Color(0xFFB0D18B)
val onTertiaryFixedVariantLight = Color(0xFF713342)
val mainBannerScrimLight = Color(0x824E7477)
val onMainBannerScrimLight = Color(0xFFFFFFFF)
val communityBannerColorLight = Color(0xFF288BFF)
val onCommunityBannerColorLight = Color(0xFFFFFFFF)

val recordBestAccuracyLight = Color(0xFF89c724)
val recordNormalAccuracyLight = Color(0xFFf2bd00)
val recordBadAccuracyLight = Color(0xFFF0380F)
val recordWorstAccuracyLight = Color(0xFFF00F0F)
val recordUndefinedAccuracyLight = Color(0xFFF00F0F)


val primaryFixedDark = Color(0xFFD9E2FF)
val onPrimaryFixedDark = Color(0xFF001A43)
val primaryFixedDimDark = Color(0xFFAFC6FF)
val onPrimaryFixedVariantDark = Color(0xFF2D4678)
val secondaryFixedDark = Color(0xFFAEECFF)
val onSecondaryFixedDark = Color(0xFF001F26)
val secondaryFixedDimDark = Color(0xFF85D2E7)
val onSecondaryFixedVariantDark = Color(0xFF004E5D)
val tertiaryFixedDark = Color(0xFFFFD9DF)
val onTertiaryFixedDark = Color(0xFF3A0717)
val tertiaryFixedDimDark = Color(0xFFFFB1C0)
val onTertiaryFixedVariantDark = Color(0xFF713342)
val mainBannerScrimDark = Color(0x824E7477)
val onMainBannerScrimDark = Color(0xFFFFFFFF)
val communityBannerColorDark = Color(0xFF288BFF)
val onCommunityBannerColorDark = Color(0xFFFFFFFF)

val recordBestAccuracyDark = Color(0xFF89c724)
val recordNormalAccuracyDark = Color(0xFFf2bd00)
val recordBadAccuracyDark = Color(0xFFF0380F)
val recordWorstAccuracyDark = Color(0xFFF00F0F)
val recordUndefinedAccuracyDark = Color(0xFFF00F0F)
